<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Md to Html</title>

  <!-- Bootstrap -->
  <link href="../../css/plugins/bootstrap.min.css" rel="stylesheet">
  <link href="../../css/plugins/bootstrap-theme.min.css" rel="stylesheet">
  <link href="../../css/main.css" rel="stylesheet">
  <!--<link href="css/custom.css" rel="stylesheet">-->

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../../js/bootstrap.min.js"></script>
  <script src="../../js/custom/custom.js"></script>
  <script src="../../js/custom/input.js"></script>
  <script src="../../js/custom/login.js"></script>


    <div class="container">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading no-padding">
            <div class="container">
              <div class="row">
                <div class="col-lg-6"></div>
                <div  class="col-lg-2 text-right"><h5 class="text-right text-primary">Hello, <?=$_SESSION['username']?>!</h5></div>
                <div class="col-lg-2 text-center"><a href="www.google.si"><h5>Edit profile</h5></a></div>
                <div class="col-lg-2"><a id='logout' class="text-left" href="logout.php"><h5>Logout</h5></a></div>
              </div>

            </div>


          </div>


          </div>
        </div>
      </div>
  <!--
    <div class="container panel-success">
      <div class="row"></div>
      <div class="row panel panel-default">


        <div class="col-lg-6"></div>
        <div class="col-lg-2 text-right"><h5 class="text-right text-primary">Hello, <?=$_SESSION['username']?>!</h5></div>
        <div class="col-lg-2 text-center"><a href="www.google.si"><h5>Edit profile</h5></a></div>
        <div class="col-lg-2"><a class="text-left" href="www.google.si"><h5>Logout</h5></a></div>
      </div>

    </div>
    -->
  <section class="container">
    <div class="col-lg-12">
      <h1>Editor</h1>
      <div class="row">
        <div class="col-lg-12">

          <div class="panel panel-default settings-panel">

            <form class="form-inline form-vertical" role="form">
                <input type="hidden" name="document-id" value="<?= !empty($this->element) ? $this->element['DocumentID'] : null ?>"/>
              <div class="form-group">
                <input name="docName" class="form-control" value="<?= !empty($this->element) ? $this->element['DocumentName'] : null ?>" placeholder="Name" type="text">
              </div>
              <div class="form-group">
                <input id="prvi" name="alias" class="form-control small-margin-left" value="<?= !empty($this->element) ? $this->element['Alias'] : null ?>" placeholder="Alias" type="text">
              </div>
              <div class="form-group">
                <input name="tags" class="form-control small-margin-left" value="<?= !empty($this->element) ? $this->element['Tags'] : null ?>" placeholder="Tags" type="text">
              </div>
              <div class="form-group form-vertical">
                <button id="btn" type="button" data-action="save" class="btn btn-primary btn-md small-margin-left btn-block" disabled="disabled">Save</button>

              </div>
              <div class="form-group form-vertical">

                <a href="index.php?c=index&a=showList" style="margin-left:285%" class="btn btn-primary">Back to list</a>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>


    <form name="Editing">
      <div class="editor-wrapper col-lg-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            Editor
          </div>
          <div class="panel-body">
            <div class="col-sm-6 left no-padding">
              <div class="form-group">
                <label class="novi" for="Code">Code</label>
                <textarea name="textleft" class="form-control" rows="5" id="comment">
                  <?= !empty($this->element) ? $this->element['Text'] : NULL ?>
                </textarea>
              </div>
            </div>
            <div class="col-sm-6 right no-padding">
              <div class="form-group">
                <label class="novi" for="Code">Preview</label>
                <div class="md-preview">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>


  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

</body>
</html>