<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Forgot password</title>

    <!-- Bootstrap -->
    <link href="../../css/plugins/bootstrap.min.css" rel="stylesheet">
    <link href="../../css/plugins/bootstrap-theme.min.css" rel="stylesheet">
    <link href="../../css/messagebox.css" rel="stylesheet">
    <link href="../../css/main.css" rel="stylesheet">
    <link href="../../css/login.css" rel="stylesheet">
    <!--<link href="css/custom.css" rel="stylesheet">-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="container resetPass">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">

                <h3 class="text-primary text-center">Reset password</h3>
                <div class="panel-heading">
                    <hr>
                </div>

                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="newPass" action="" method="post" role="form" style="display: block;">
                                <input type="hidden" name="activation" id="activation" value="<?php print($_REQUEST['rp'])?>">
                                <div class="form-group">
                                   <input type="password" name="password" id="password" tabindex="2" class="form-control inp" placeholder="Password">
                                   
                                </div>
                                <div class="form-group">
                                    <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control inp" placeholder="Confirm Password">
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn-info" value="Change password">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-6 col-sm-offset-3">
                                        <a name="goHome" id="goHome" tabindex="4" href="index.php" class="text-center center-block">Go home</a>
                                    </div>
                                </div>


                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</body>



<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="../../js/bootstrap.min.js"></script>
<script src="../../js/custom/custom.js"></script>
<script src="../../js/custom/resetPass.js"></script>
<script src="../../js/custom/input.js"></script>
<script src="../../js/messagebox.js"></script>
<script src="../../js/messagebox.min.js"></script>


</body>
</html>